# Generated by Django 2.0.1 on 2018-02-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='commod',
        ),
        migrations.AddField(
            model_name='orders',
            name='commod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Cat'),
        ),
    ]
